import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className='w-full h-screen bg-gradient-to-br from-violet-900 to-fuchsia-800 overflow-auto relative'>
          <div
            className='fixed inset-0'
            style={{
              backgroundImage: `radial-gradient(rgba(192, 132, 252, .2) 2px, transparent 0)`,
              backgroundSize: "15px 15px",
              backgroundPosition: "-16.5px -16.5px",
              maskImage: `radial-gradient(ellipse at center, rgba(0, 0, 0, 1), transparent 75%)`
            }}
          />
          <div className='relative min-h-screen w-full max-w-screen-sm mx-auto z-10'>
            {/* <Nav /> */}
            <div className='w-full px-4 py-12'>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
